project/main/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from accounts import urls as accounts_urls
from accounts.views import index, superuser
from stats import urls as stats_urls
from tickets import urls as tickets_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("admin/", superuser, name="superuser"),
    path("", index, name="index"),
    path("accounts/", include(accounts_urls)),
    path("statistics/", include(stats_urls)),
    path("tickets/", include(tickets_urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

project/tickets/urls.py
from django.urls import path
from tickets.views import (
    tickets_new_bug, tickets_new_feature, tickets_view_one,
    tickets_view_all, tickets_edit, tickets_delete,
    upvote_add, upvote_remove, admin_ticket_status)


urlpatterns = [
    path("", tickets_view_all, name="tickets_view_all"),
    path("bug/new", tickets_new_bug, name="tickets_new_bug"),
    path("feature/new", tickets_new_feature, name="tickets_new_feature"),
    path("<int:pk>", tickets_view_one, name="tickets_view_one"),
    path("edit/<int:pk>", tickets_edit, name="tickets_edit"),
    path("delete/<int:pk>", tickets_delete, name="tickets_delete"),
    path("upvote/add/<int:pk>", upvote_add, name="upvote_add"),
    path("upvote/remove/<int:pk>", upvote_remove, name="upvote_remove"),
    path("admin/edit-status/<int:pk>",
        admin_ticket_status,
        name="admin_ticket_status"),
]

project/tickets/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# ----- TICKET TYPE ----- #
class TicketType(models.Model):
    TICKET_TYPE_CHOICES = (
        ("Bug", "Bug"),
        ("Feature", "Feature")
    )
    ticket_type = models.CharField(
        max_length=7,
        unique=True,
        choices=TICKET_TYPE_CHOICES)

    class Meta:
        verbose_name = ("Ticket Type")
        verbose_name_plural = ("Ticket Types")

    def __str__(self):
        return self.ticket_type


# ----- TICKET STATUS ----- #
class TicketStatus(models.Model):
    TICKET_STATUS_CHOICES = (
        ("Open", "Open"),
        ("In Progress", "In Progress"),
        ("Closed", "Closed"),
    )
    ticket_status = models.CharField(
        max_length=11,
        unique=True,
        choices=TICKET_STATUS_CHOICES)

    class Meta:
        verbose_name = ("Ticket Status")
        verbose_name_plural = ("Ticket Status")

    def __str__(self):
        return self.ticket_status


# ----- TICKETS ----- #
class Ticket(models.Model):
    """
    Allow users to open Tickets (Bugs or Features).
    Default status should be 'Open' with current timestamp.
    """
    # user fields (editable)
    title = models.CharField(
        max_length=75,
        default="",
        blank=False)
    description = models.TextField(
        max_length=2000,
        default="",
        blank=False)

    # ticket fields (non-editable)
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE)
    ticket_status = models.ForeignKey(
        TicketStatus,
        null=True,
        on_delete=models.CASCADE)
    ticket_type = models.ForeignKey(
        TicketType,
        null=True,
        on_delete=models.CASCADE)
    date_created = models.DateTimeField(
        blank=False,
        null=False,
        auto_now_add=True)
    date_edited = models.DateTimeField(
        blank=False,
        null=False,
        default=timezone.now)
    views = models.IntegerField(
        default=0)
    upvotes = models.IntegerField(
        default=0)
    total_donations = models.IntegerField(
        default=0)

    class Meta:
        ordering = ("-date_edited", )

    def __str__(self):
        return "#{0} [{1}] - {2}".format(
            self.id, self.ticket_type, self.title)


# ----- COMMENTS ----- #
class Comment(models.Model):
    """ Allow users to add Comments onto Tickets (Bugs or Features). """
    # user fields (editable)
    comment = models.TextField(
        max_length=2000,
        null=True)

    # comment fields (non-editable)
    ticket = models.ForeignKey(
        Ticket,
        null=True,
        on_delete=models.CASCADE)
    commenter = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE)
    date_commented = models.DateTimeField(
        auto_now_add=True)

    def __str__(self):
        return "Comment #{0} by {1} on Ticket #{2}".format(
            self.id, self.commenter, self.ticket.id)


# ----- UPVOTES ----- #
class Upvote(models.Model):
    """ Allow users to Upvote a Ticket (Bugs or Features) """
    user = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE)
    ticket = models.ForeignKey(
        Ticket,
        null=True,
        on_delete=models.CASCADE)

    def __str__(self):
        return "Upvote by {0} on Ticket {1}".format(
            self.user.username, self.ticket.id)

project/tickets/forms.py
import calendar
from datetime import datetime
from django import forms
from tickets.models import Ticket, Comment


# ----- TICKETS ----- #
class TicketForm(forms.ModelForm):
    """ Form to allow User to submit new Ticket """
    title = forms.CharField(
        label="Title of Ticket",
        min_length=5,
        max_length=75,
        widget=forms.TextInput(),
        required=True)
    description = forms.CharField(
        label="Ticket Details",
        min_length=20,
        max_length=2000,
        widget=forms.Textarea(),
        required=True)

    class Meta:
        model = Ticket
        fields = ["title", "description"]


# ----- DONATIONS ----- #
class DonationForm(forms.Form):
    donation_amount = forms.IntegerField(
        label="Donation Amount",
        widget=forms.NumberInput(
            attrs={
                "type": "range", "step": "5", "value": "10",
                "min": "5", "max": "100"}),
        required=False)


# ----- COMMENTS ----- #
class CommentForm(forms.ModelForm):
    """ Form to allow Users to add Comments on Tickets """
    comment = forms.CharField(
        label="Your Comment",
        min_length=5,
        max_length=2000,
        widget=forms.Textarea(),
        required=True)

    class Meta:
        model = Comment
        fields = ["comment"]

project/tickets/views.py
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from accounts.models import Profile
from tickets.models import Ticket, TicketStatus, TicketType, Comment, Upvote
from tickets.forms import TicketForm, CommentForm, DonationForm
import stripe


stripe.api_key = settings.STRIPE_SECRET


def tickets_view_all(request):
    """ View ALL Tickets """
    # search parameters
    page = request.GET.get("page", 1)
    ticket_status_list = TicketStatus.objects.all()
    ticket_type_list = TicketType.objects.all()
    tkt_status = request.GET.get("tkt_status")
    tkt_type = request.GET.get("tkt_type")
    upvotes_min = request.GET.get("upvotes_min")
    upvotes_max = request.GET.get("upvotes_max")
    views_min = request.GET.get("views_min")
    views_max = request.GET.get("views_max")
    # filter by search parameters
    tickets = Ticket.objects.all()
    tickets = tickets.filter(
        ticket_status__id=tkt_status) if tkt_status else tickets
    tickets = tickets.filter(
        ticket_type__id=tkt_type) if tkt_type else tickets
    tickets = tickets.filter(
        upvotes__gte=upvotes_min) if upvotes_min else tickets
    tickets = tickets.filter(
        upvotes__lte=upvotes_max) if upvotes_max else tickets
    tickets = tickets.filter(
        views__gte=views_min) if views_min else tickets
    tickets = tickets.filter(
        views__lte=views_max) if views_max else tickets
    # pagination
    paginator = Paginator(tickets, 6)
    try:
        tickets = paginator.page(page)
    except PageNotAnInteger:
        tickets = paginator.page(1)
    except EmptyPage:
        tickets = paginator.page(paginator.num_pages)
    # pass context to template
    context = {
        "tickets": tickets,
        "ticket_status_list": ticket_status_list,
        "ticket_type_list": ticket_type_list,
        "tkt_status": tkt_status,
        "tkt_type": tkt_type,
        "upvotes_min": upvotes_min,
        "upvotes_max": upvotes_max,
        "views_min": views_min,
        "views_max": views_max,
    }
    return render(request, "tickets_view_all.html", context)


@login_required
def tickets_new_bug(request):
    """ Create a NEW Ticket (Bug) """
    if request.method == "POST":
        ticket_form = TicketForm(request.POST)
        if ticket_form.is_valid():
            ticket_form.instance.author = request.user
            ticket_form.instance.ticket_type_id = 1
            ticket_form.instance.ticket_status_id = 1
            new_ticket = ticket_form.save()
            new_ticket_id = new_ticket.pk
            messages.success(
                request, f"Thank you for your Bug Report!")
            return redirect(tickets_view_one, new_ticket_id)
    else:
        ticket_form = TicketForm()
    context = {
        "ticket_form": ticket_form,
    }
    return render(request, "tickets_new_bug.html", context)


@login_required
def tickets_new_feature(request):
    """ Create a NEW Ticket (Feature) """
    if request.method == "POST":
        ticket_form = TicketForm(request.POST)
        donation_form = DonationForm(request.POST)
        if ticket_form.is_valid() and donation_form.is_valid():
            # amount to pay / donate
            donation_amount = 0
            donation_amount += int(request.POST.get("donation_amount"))
            try:
                # build Stripe payment
                token = request.POST["stripeToken"]
                customer = stripe.Charge.create(
                    amount=int(donation_amount * 100),
                    currency="EUR",
                    description=(
                        request.user.email +
                        " (" + request.user.get_full_name() + ")"),
                    source=token,
                )
            except stripe.error.CardError:
                # Stripe payment error
                messages.error(request, f"Your card was declined!")
            # authorization is valid - payment successful
            if customer.paid:
                ticket_form.instance.author = request.user
                ticket_form.instance.ticket_type_id = 2
                ticket_form.instance.total_donations = donation_amount
                # update user Profile with additional donation amount
                get_user_donations = Profile.objects.values_list(
                    "total_donated", flat=True).get(user_id=request.user.id)
                new_user_donations = get_user_donations + donation_amount
                Profile.objects.filter(
                    user_id=request.user.id).update(
                        total_donated=new_user_donations)
                # update ticket status to In Progress if €100 goal is achieved
                if donation_amount >= int(100):
                    ticket_form.instance.ticket_status_id = 2
                else:
                    ticket_form.instance.ticket_status_id = 1
                new_ticket = ticket_form.save()
                new_ticket_id = new_ticket.pk
                messages.success(
                    request, f"Thank you for your Feature Request!\
                        €{donation_amount} was charged to your card.")
                return redirect(tickets_view_one, new_ticket_id)
            else:
                messages.error(request, f"Unable to take payment!")
        else:
            messages.error(request, f"There was an error. Please try again.")
    else:
        ticket_form = TicketForm()
        donation_form = DonationForm()
    context = {
        "donation_form": donation_form,
        "ticket_form": ticket_form,
        "publishable": settings.STRIPE_PUBLISHABLE
    }
    return render(request, "tickets_new_feature.html", context)


def tickets_view_one(request, pk):
    """ View a Single Ticket """
    # get ticket details
    ticket = get_object_or_404(Ticket, pk=pk)
    # increase number of views by 1
    ticket.views += 1
    ticket.save()
    # filter comments on specific ticket
    comments = Comment.objects.filter(ticket_id=ticket.pk)
    # filter upvotes on specific ticket by user ID
    upvotes = Upvote.objects.filter(ticket_id=ticket.pk).values("user_id")
    voters = [vote["user_id"] for vote in upvotes]
    donors = User.objects.filter(id__in=voters)
    # render drop-down list for superusers to update status
    ticket_status_list = TicketStatus.objects.all()
    tkt_status = ticket.ticket_status.id
    # POST methods
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment_form.instance.commenter = request.user
            comment_form.instance.ticket = ticket
            comment_form.save()
            # remove two ticket views to avoid duplicates on POST
            ticket.views -= 2
            ticket.save()
            messages.success(
                request, f"Comment successfully added!")
            return redirect(tickets_view_one, ticket.pk)
    else:
        comment_form = CommentForm()
        donation_form = DonationForm()
    context = {
        "comment_form": comment_form,
        "comments": comments,
        "donation_form": donation_form,
        "donors": donors,
        "publishable": settings.STRIPE_PUBLISHABLE,
        "ticket": ticket,
        "ticket_status_list": ticket_status_list,
        "tkt_status": tkt_status,
        "voters": voters,
    }
    return render(request, "tickets_view_one.html", context)


@login_required
def tickets_edit(request, pk):
    """ Edit a Single Ticket """
    ticket = get_object_or_404(Ticket, pk=pk)
    if request.method == "POST":
        ticket_form = TicketForm(request.POST, instance=ticket)
        if ticket_form.is_valid():
            ticket_form.instance.date_edited = timezone.now()
            ticket_form.save()
            messages.success(
                request, f"Ticket successfully updated!")
            return redirect(tickets_view_one, ticket.pk)
    else:
        ticket_form = TicketForm(instance=ticket)
    context = {
        "ticket": ticket,
        "ticket_form": ticket_form,
    }
    return render(request, "tickets_edit.html", context)


@login_required
def tickets_delete(request, pk):
    """ Delete a Ticket """
    ticket = get_object_or_404(Ticket, pk=pk)
    ticket.delete()
    messages.success(
        request, f"Your ticket has been deleted!")
    return redirect(tickets_view_all)


@login_required
def upvote_add(request, pk):
    """ Upvote a Ticket """
    ticket = get_object_or_404(Ticket, pk=pk)
    ticket.upvotes += 1
    # remove a ticket view to avoid duplicates
    ticket.views -= 1
    ticket.save()
    if request.method == "POST":
        donation_form = DonationForm(request.POST)
        if donation_form.is_valid():
            # amount to pay / donate
            donation_amount = 0
            donation_amount += int(request.POST.get("donation_amount"))
            try:
                # build Stripe payment
                token = request.POST["stripeToken"]
                customer = stripe.Charge.create(
                    amount=int(donation_amount * 100),
                    currency="EUR",
                    description=(
                        request.user.email +
                        " (" + request.user.get_full_name() + ")"),
                    source=token,
                )
            except stripe.error.CardError:
                # Stripe payment error
                messages.error(request, f"Your card was declined!")
            # authorization is valid - payment successful
            if customer.paid:
                Upvote.objects.create(
                    ticket_id=ticket.pk,
                    user_id=request.user.id)

project/tickets/templates/partials/comments.html
{% load materializecss %}
{% load humanize %}
<div class="card form white-text text-shadow-2">
    <h1 class="bold center-align" id="comments">
        <i class="fas fa-comments"></i>
        <span class="font-londrina">Comments</span>
        <!-- show total number of comments -->
        (<span class="{% include './ticket_status_color.html' %}-text">{{ comments|length }}</span>)
    </h1>

    <div class="card-content white-text">

        <ul class="collection">
            {% for comment in comments %}
                <!-- add each comment to a collection -->
                <li class="collection-item avatar grey darken-4">
                    <img src="{{ comment.commenter.profile.image.url }}" alt="{{ comment.commenter }}" class="circle white"
                        lazyload="on">
                    <span class="title {% include './ticket_status_color.html' %}-text bold">
                        {{ comment.commenter.username }}
                    </span>|
                    <small>
                        <span class="{% include './ticket_status_color.html' %}-text text-lighten-2">
                            {{ comment.date_commented|date:"dMy @G:i-T"|upper }}
                        </span>
                        (<span class="{% include './ticket_status_color.html' %}-text text-lighten-4">
                            {{ comment.date_commented|naturaltime }}
                        </span>)
                    </small>
                    <p>
                        {{ comment.comment|linebreaksbr }}
                    </p>
                </li>
            {% endfor %}
        </ul>

        {% if user.is_authenticated %}
            <!-- allow users that are logged-in to post a new comment -->
            {% if ticket.ticket_status.ticket_status == "Closed" %}
                <!-- disable comments if ticket is closed -->
                <div class="center-align bold">
                    Ticket and Comments are now closed.<br>
                    Want to open a new
                    <a href="{% url 'tickets_new_'|add:ticket.ticket_type.ticket_type|lower %}" class="bold">
                        {{ ticket.ticket_type.ticket_type }} Ticket
                    </a>?
                </div>
            {% else %}
                <!-- user is logged in and ticket status is not Closed || allow comments -->
                <form method="POST">
                    {% csrf_token %}
                    <textarea name="comment" id="id_comment" cols="40" rows="10" minlength="5" maxlength="2000"
                        placeholder="[{{ user.username }}] add a new comment ..."></textarea>
                    <button type="submit" class="btn green bold text-shadow-2" formaction="#comments">Comment</button>
                </form>
            {% endif %}
        {% else %}
            <!-- if not logged-in, redirect to login/register pages -->
            <div class="center-align bold">
                Please
                <a href="{% url 'login' %}" class="title {% include './ticket_status_color.html' %}-text">Log in</a> or
                <a href="{% url 'register' %}" class="title {% include './ticket_status_color.html' %}-text">Register</a>
                to add comments.
            </div>
        {% endif %}

    </div>
</div>

project/tickets/templates/partials/date_edited.html
{% load humanize %}
<!-- this is used in several scenarios, so is best as a partial -->
<span class="{% include './ticket_status_color.html' %}-text">
    <h1 class="i-stats">
        <i class="far fa-calendar-check tooltipped" data-position="bottom" data-tooltip="LAST UPDATED"></i>
    </h1>
</span>
{{ ticket.date_edited|naturalday:"d E, Y"|upper }}<br>
<small>{{ ticket.date_edited|time:"@H:i (T)" }}</small>

project/tickets/templates/partials/pagination.html
<ul class="pagination center-align form">
    {% if tickets.has_previous %}
    <!-- display pagination 'back' buttons -->
    <li>
        <a href="?page=1{{ get_args }}#filter" class="green-text">
            <i class="fas fa-angle-double-left"></i>
        </a>
    </li>
    <li>
        <a href="?page={{ tickets.previous_page_number }}{{ get_args }}#filter" class="green-text">
            <i class="fas fa-angle-left"></i>
        </a>
    </li>
    {% endif %}

    {% for num in tickets.paginator.page_range %}
        <!-- loop through pagination 'page' numbers -->
        {% if tickets.number == num %}
            <!-- set 'active' class but disable the 'current page -->
            <li class="active disabled green text-shadow-2">
                <a class="white-text">{{ num }}</a>
            </li>
        {% elif num > tickets.number|add:'-3' and num < tickets.number|add:'3' %}
            <!-- get the previous 2 and next 2 page numbers -->
            <li>
                <a href="?page={{ num }}{{ get_args }}#filter" class="white-text">{{ num }}</a>
            </li>
        {% endif %}
    {% endfor %}

    {% if tickets.has_next %}
    <!-- display pagination 'next' buttons -->
    <li>
        <a href="?page={{ tickets.next_page_number }}{{ get_args }}#filter" class="green-text">
            <i class="fas fa-angle-right"></i>
        </a>
    </li>
    <li>
        <a href="?page={{ tickets.paginator.num_pages }}{{ get_args }}#filter" class="green-text">
            <i class="fas fa-angle-double-right"></i>
        </a>
    </li>
    {% endif %}
</ul>

project/tickets/templates/partials/status_color.html
{% if ticket.ticket_status.ticket_status == 'Open' %}red{% elif ticket.ticket_status.ticket_status == 'In Progress' %}amber{% elif ticket.ticket_status.ticket_status == 'Closed' %}green{% endif %}

project/tickets/templates/partials/ticket_badge.html
<div class="card-badge-div">
    <span class="card-badge card-badge-{{ ticket.ticket_type.ticket_type|lower }}">
        {% if ticket.ticket_type.ticket_type == 'Bug' %}
        <!-- bug -->
        <i class="fas fa-bug fa-lg" aria-hidden="true"></i>
        {% elif ticket.ticket_type.ticket_type == 'Feature' %}
        <!-- feature -->
        <i class="fas fa-magic fa-lg" aria-hidden="true"></i>
        {% endif %}
    </span>
</div>

project/tickets/templates/partials/ticket_card.html
<!-- link to ticket display -->
<a href="{% url 'tickets_view_one' ticket.id %}">
    <div class="col s12 m6">
        <div class="card form bold white-text text-shadow-2 hoverable">

            <!-- top-right corner badge based on ticket status -->
            {% include "./ticket_badge.html" %}

            <!-- Ticket Title & Description -->
            <div class="card-content white-text">
                <h2 class="bold truncate">
                    #{{ ticket.id }}
                    <br>
                    <small>
                        Type:
                        <span class="{% include './ticket_type_color.html' %}-text">
                            {{ ticket.ticket_type|upper }}
                        </span>
                        <br>
                        Status:
                        <span class="{% include './ticket_status_color.html' %}-text">
                            {{ ticket.ticket_status|upper }}
                        </span>
                        <br>
                        Author:
                        <img src="{{ ticket.author.profile.image.url }}" style="vertical-align:middle" width="25"
                            height="25" alt="{{ ticket.author }}" class="circle white" lazyload="on">
                        {{ ticket.author.username }}
                    </small>
                </h2>

                <div class="divider"></div>

                <span class="card-title truncate">
                    {{ ticket.title }}
                </span>
                <p class="truncate">
                    <i class="fas fa-info-circle white-text" title="{{ ticket.description }}"></i>
                    {{ ticket.description }}
                </p>
            </div>

            <!-- Ticket Stats -->
            <div class="card-action {% include './ticket_status_color.html' %} darken-5">
                <div class="row center-align">
                    <div class="col s4 tooltipped" data-position="top" data-tooltip="UPVOTES">
                        <i class="far fa-thumbs-up fa-lg" aria-hidden="true"></i><br>
                        <span class="white-text">{{ ticket.upvotes }}</span>
                    </div>
                    <div class="col s4 tooltipped" data-position="top" data-tooltip="VIEWS">
                        <i class="far fa-eye fa-lg" aria-hidden="true"></i><br>
                        <span class="white-text">{{ ticket.views }}</span>
                    </div>
                    <div class="col s4 tooltipped" data-position="top" data-tooltip="DONATIONS">
                        <i class="fas fa-hand-holding-usd fa-lg" aria-hidden="true"></i><br>
                        <span class="white-text">
                            {% if ticket.ticket_type.ticket_type == 'Feature' %}
                            &euro;{{ ticket.total_donations }}
                            {% else %}
                            FREE
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>

        </div>
    </div>
</a>

project/tickets/templates/partials/ticket_filter.html
<div class="row">
    <h1 class="white-text center-align upper font-londrina" id="filter">Filter Tickets</h1>

    <!-- Form for Searching / Filtering Tickets -->
    <form action="." method="GET" class="form white-text">
        <div class="row">

            <!-- filter drop-downs -->
            <div class="col s6 l3">
                <fieldset class="fieldset-filter grey darken-4 center-align">
                    <legend>
                        <h2>Ticket</h2>
                    </legend>
                    <!-- filter by TICKET STATUS -->
                    <select name="tkt_status" id="tkt_status" class="browser-default">
                        <option value="">Status</option>
                        {% for status in ticket_status_list %}
                        <option value="{{ status.id }}" {% if status.id|safe in tkt_status|safe %}selected{% endif %}>
                            {{ status }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <!-- filter by TICKET TYPE -->
                    <select name="tkt_type" id="tkt_type" class="browser-default">
                        <option value="">Type</option>
                        {% for type in ticket_type_list %}
                        <option value="{{ type.id }}" {% if type.id|safe in tkt_type|safe %}selected{% endif %}>
                            {{ type }}
                        </option>
                        {% endfor %}
                    </select>
                </fieldset>
            </div>

            <!-- filter by VOTES -->
            <div class="col s6 l3">
                <fieldset class="fieldset-filter grey darken-4 center-align">
                    <legend>
                        <h2>Votes</h2>
                    </legend>
                    <input type="number" id="upvotes_min" class="validate" name="upvotes_min"
                        value="{% if upvotes_min  %}{{ upvotes_min }}{% endif %}" placeholder="MIN">
                    <label for="upvotes_min" class="hide"></label>
                    <br>
                    <input type="number" id="upvotes_max" class="validate" name="upvotes_max"
                        value="{% if upvotes_max  %}{{ upvotes_max }}{% endif %}" placeholder="MAX">
                    <label for="upvotes_max"></label>
                </fieldset>
            </div>

            <!-- filter by VIEWS -->
            <div class="col s6 l3">
                <fieldset class="fieldset-filter grey darken-4 center-align">
                    <legend>
                        <h2>Views</h2>
                    </legend>
                    <input type="number" id="views_min" class="validate" name="views_min"
                        value="{% if views_min  %}{{ views_min }}{% endif %}" placeholder="MIN">
                    <label for="views_min"></label>
                    <br>
                    <input type="number" id="views_max" class="validate" name="views_max"
                        value="{% if views_max  %}{{ views_max }}{% endif %}" placeholder="MAX">
                    <label for="views_max"></label>
                </fieldset>
            </div>

            <!-- Filter buttons -->
            <div class="col s6 l3">
                <fieldset class="fieldset-filter grey darken-4 center-align">
                    <legend>
                        <h2>Filter</h2>
                    </legend>
                    <button type="submit" class="btn blue bold text-shadow-2"
                        formaction="#filter">Search</button><br><br>
                    <a href="{% url 'tickets_view_all' %}" class="btn red bold text-shadow-2">
                        Reset
                    </a>
                </fieldset>
            </div>

        </div>
    </form>
</div>

project/tickets/templates/partials/ticket_status_color.html
{% if ticket.ticket_status.ticket_status == 'Open' %}red{% elif ticket.ticket_status.ticket_status == 'In Progress' %}amber{% elif ticket.ticket_status.ticket_status == 'Closed' %}green{% endif %}

project/tickets/templates/partials/ticket_type_color.html
{% if ticket.ticket_type.ticket_type == 'Bug' %}bug{% elif ticket.ticket_type.ticket_type == 'Feature' %}feature{% endif %}