project/main/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from accounts import urls as accounts_urls
from accounts.views import index, superuser
from stats import urls as stats_urls
from tickets import urls as tickets_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("admin/", superuser, name="superuser"),
    path("", index, name="index"),
    path("accounts/", include(accounts_urls)),
    path("statistics/", include(stats_urls)),
    path("tickets/", include(tickets_urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

project/tickets/urls.py
from django.urls import path
from tickets.views import (
    tickets_new_bug, tickets_new_feature, tickets_view_one,
    tickets_view_all, tickets_edit, tickets_delete,
    upvote_add, upvote_remove, admin_ticket_status)


urlpatterns = [
    path("", tickets_view_all, name="tickets_view_all"),
    path("bug/new", tickets_new_bug, name="tickets_new_bug"),
    path("feature/new", tickets_new_feature, name="tickets_new_feature"),
    path("<int:pk>", tickets_view_one, name="tickets_view_one"),
    path("edit/<int:pk>", tickets_edit, name="tickets_edit"),
    path("delete/<int:pk>", tickets_delete, name="tickets_delete"),
    path("upvote/add/<int:pk>", upvote_add, name="upvote_add"),
    path("upvote/remove/<int:pk>", upvote_remove, name="upvote_remove"),
    path("admin/edit-status/<int:pk>",
        admin_ticket_status,
        name="admin_ticket_status"),
]

project/tickets/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# ----- TICKET TYPE ----- #
class TicketType(models.Model):
    TICKET_TYPE_CHOICES = (
        ("Bug", "Bug"),
        ("Feature", "Feature")
    )
    ticket_type = models.CharField(
        max_length=7,
        unique=True,
        choices=TICKET_TYPE_CHOICES)

    class Meta:
        verbose_name = ("Ticket Type")
        verbose_name_plural = ("Ticket Types")

    def __str__(self):
        return self.ticket_type


# ----- TICKET STATUS ----- #
class TicketStatus(models.Model):
    TICKET_STATUS_CHOICES = (
        ("Open", "Open"),
        ("In Progress", "In Progress"),
        ("Closed", "Closed"),
    )
    ticket_status = models.CharField(
        max_length=11,
        unique=True,
        choices=TICKET_STATUS_CHOICES)

    class Meta:
        verbose_name = ("Ticket Status")
        verbose_name_plural = ("Ticket Status")

    def __str__(self):
        return self.ticket_status


# ----- TICKETS ----- #
class Ticket(models.Model):
    """
    Allow users to open Tickets (Bugs or Features).
    Default status should be 'Open' with current timestamp.
    """
    # user fields (editable)
    title = models.CharField(
        max_length=75,
        default="",
        blank=False)
    description = models.TextField(
        max_length=2000,
        default="",
        blank=False)

    # ticket fields (non-editable)
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE)
    ticket_status = models.ForeignKey(
        TicketStatus,
        null=True,
        on_delete=models.CASCADE)
    ticket_type = models.ForeignKey(
        TicketType,
        null=True,
        on_delete=models.CASCADE)
    date_created = models.DateTimeField(
        blank=False,
        null=False,
        auto_now_add=True)
    date_edited = models.DateTimeField(
        blank=False,
        null=False,
        default=timezone.now)
    views = models.IntegerField(
        default=0)
    upvotes = models.IntegerField(
        default=0)
    total_donations = models.IntegerField(
        default=0)

    class Meta:
        ordering = ("-date_edited", )

    def __str__(self):
        return "#{0} [{1}] - {2}".format(
            self.id, self.ticket_type, self.title)


# ----- COMMENTS ----- #
class Comment(models.Model):
    """ Allow users to add Comments onto Tickets (Bugs or Features). """
    # user fields (editable)
    comment = models.TextField(
        max_length=2000,
        null=True)

    # comment fields (non-editable)
    ticket = models.ForeignKey(
        Ticket,
        null=True,
        on_delete=models.CASCADE)
    commenter = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE)
    date_commented = models.DateTimeField(
        auto_now_add=True)

    def __str__(self):
        return "Comment #{0} by {1} on Ticket #{2}".format(
            self.id, self.commenter, self.ticket.id)


# ----- UPVOTES ----- #
class Upvote(models.Model):
    """ Allow users to Upvote a Ticket (Bugs or Features) """
    user = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE)
    ticket = models.ForeignKey(
        Ticket,
        null=True,
        on_delete=models.CASCADE)

    def __str__(self):
        return "Upvote by {0} on Ticket {1}".format(
            self.user.username, self.ticket.id)

project/tickets/forms.py
import calendar
from datetime import datetime
from django import forms
from tickets.models import Ticket, Comment


# ----- TICKETS ----- #
class TicketForm(forms.ModelForm):
    """ Form to allow User to submit new Ticket """
    title = forms.CharField(
        label="Title of Ticket",
        min_length=5,
        max_length=75,
        widget=forms.TextInput(),
        required=True)
    description = forms.CharField(
        label="Ticket Details",
        min_length=20,
        max_length=2000,
        widget=forms.Textarea(),
        required=True)

    class Meta:
        model = Ticket
        fields = ["title", "description"]


# ----- DONATIONS ----- #
class DonationForm(forms.Form):
    donation_amount = forms.IntegerField(
        label="Donation Amount",
        widget=forms.NumberInput(
            attrs={
                "type": "range", "step": "5", "value": "10",
                "min": "5", "max": "100"}),
        required=False)


# ----- COMMENTS ----- #
class CommentForm(forms.ModelForm):
    """ Form to allow Users to add Comments on Tickets """
    comment = forms.CharField(
        label="Your Comment",
        min_length=5,
        max_length=2000,
        widget=forms.Textarea(),
        required=True)

    class Meta:
        model = Comment
        fields = ["comment"]

project/tickets/views.py
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from accounts.models import Profile
from tickets.models import Ticket, TicketStatus, TicketType, Comment, Upvote
from tickets.forms import TicketForm, CommentForm, DonationForm
import stripe


stripe.api_key = settings.STRIPE_SECRET


def tickets_view_all(request):
    """ View ALL Tickets """
    # search parameters
    page = request.GET.get("page", 1)
    ticket_status_list = TicketStatus.objects.all()
    ticket_type_list = TicketType.objects.all()
    tkt_status = request.GET.get("tkt_status")
    tkt_type = request.GET.get("tkt_type")
    upvotes_min = request.GET.get("upvotes_min")
    upvotes_max = request.GET.get("upvotes_max")
    views_min = request.GET.get("views_min")
    views_max = request.GET.get("views_max")
    # filter by search parameters
    tickets = Ticket.objects.all()
    tickets = tickets.filter(
        ticket_status__id=tkt_status) if tkt_status else tickets
    tickets = tickets.filter(
        ticket_type__id=tkt_type) if tkt_type else tickets
    tickets = tickets.filter(
        upvotes__gte=upvotes_min) if upvotes_min else tickets
    tickets = tickets.filter(
        upvotes__lte=upvotes_max) if upvotes_max else tickets
    tickets = tickets.filter(
        views__gte=views_min) if views_min else tickets
    tickets = tickets.filter(
        views__lte=views_max) if views_max else tickets
    # pagination
    paginator = Paginator(tickets, 6)
    try:
        tickets = paginator.page(page)
    except PageNotAnInteger:
        tickets = paginator.page(1)
    except EmptyPage:
        tickets = paginator.page(paginator.num_pages)
    # pass context to template
    context = {
        "tickets": tickets,
        "ticket_status_list": ticket_status_list,
        "ticket_type_list": ticket_type_list,
        "tkt_status": tkt_status,
        "tkt_type": tkt_type,
        "upvotes_min": upvotes_min,
        "upvotes_max": upvotes_max,
        "views_min": views_min,
        "views_max": views_max,
    }
    return render(request, "tickets_view_all.html", context)


@login_required
def tickets_new_bug(request):
    """ Create a NEW Ticket (Bug) """
    if request.method == "POST":
        ticket_form = TicketForm(request.POST)
        if ticket_form.is_valid():
            ticket_form.instance.author = request.user
            ticket_form.instance.ticket_type_id = 1
            ticket_form.instance.ticket_status_id = 1
            new_ticket = ticket_form.save()
            new_ticket_id = new_ticket.pk
            messages.success(
                request, f"Thank you for your Bug Report!")
            return redirect(tickets_view_one, new_ticket_id)
    else:
        ticket_form = TicketForm()
    context = {
        "ticket_form": ticket_form,
    }
    return render(request, "tickets_new_bug.html", context)


@login_required
def tickets_new_feature(request):
    """ Create a NEW Ticket (Feature) """
    if request.method == "POST":
        ticket_form = TicketForm(request.POST)
        donation_form = DonationForm(request.POST)
        if ticket_form.is_valid() and donation_form.is_valid():
            # amount to pay / donate
            donation_amount = 0
            donation_amount += int(request.POST.get("donation_amount"))
            try:
                # build Stripe payment
                token = request.POST["stripeToken"]
                customer = stripe.Charge.create(
                    amount=int(donation_amount * 100),
                    currency="EUR",
                    description=(
                        request.user.email +
                        " (" + request.user.get_full_name() + ")"),
                    source=token,
                )
            except stripe.error.CardError:
                # Stripe payment error
                messages.error(request, f"Your card was declined!")
            # authorization is valid - payment successful
            if customer.paid:
                ticket_form.instance.author = request.user
                ticket_form.instance.ticket_type_id = 2
                ticket_form.instance.total_donations = donation_amount
                # update user Profile with additional donation amount
                get_user_donations = Profile.objects.values_list(
                    "total_donated", flat=True).get(user_id=request.user.id)
                new_user_donations = get_user_donations + donation_amount
                Profile.objects.filter(
                    user_id=request.user.id).update(
                        total_donated=new_user_donations)
                # update ticket status to In Progress if €100 goal is achieved
                if donation_amount >= int(100):
                    ticket_form.instance.ticket_status_id = 2
                else:
                    ticket_form.instance.ticket_status_id = 1
                new_ticket = ticket_form.save()
                new_ticket_id = new_ticket.pk
                messages.success(
                    request, f"Thank you for your Feature Request!\
                        €{donation_amount} was charged to your card.")
                return redirect(tickets_view_one, new_ticket_id)
            else:
                messages.error(request, f"Unable to take payment!")
        else:
            messages.error(request, f"There was an error. Please try again.")
    else:
        ticket_form = TicketForm()
        donation_form = DonationForm()
    context = {
        "donation_form": donation_form,
        "ticket_form": ticket_form,
        "publishable": settings.STRIPE_PUBLISHABLE
    }
    return render(request, "tickets_new_feature.html", context)


def tickets_view_one(request, pk):
    """ View a Single Ticket """
    # get ticket details
    ticket = get_object_or_404(Ticket, pk=pk)
    # increase number of views by 1
    ticket.views += 1
    ticket.save()
    # filter comments on specific ticket
    comments = Comment.objects.filter(ticket_id=ticket.pk)
    # filter upvotes on specific ticket by user ID
    upvotes = Upvote.objects.filter(ticket_id=ticket.pk).values("user_id")
    voters = [vote["user_id"] for vote in upvotes]
    donors = User.objects.filter(id__in=voters)
    # render drop-down list for superusers to update status
    ticket_status_list = TicketStatus.objects.all()
    tkt_status = ticket.ticket_status.id
    # POST methods
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment_form.instance.commenter = request.user
            comment_form.instance.ticket = ticket
            comment_form.save()
            # remove two ticket views to avoid duplicates on POST
            ticket.views -= 2
            ticket.save()
            messages.success(
                request, f"Comment successfully added!")
            return redirect(tickets_view_one, ticket.pk)
    else:
        comment_form = CommentForm()
        donation_form = DonationForm()
    context = {
        "comment_form": comment_form,
        "comments": comments,
        "donation_form": donation_form,
        "donors": donors,
        "publishable": settings.STRIPE_PUBLISHABLE,
        "ticket": ticket,
        "ticket_status_list": ticket_status_list,
        "tkt_status": tkt_status,
        "voters": voters,
    }
    return render(request, "tickets_view_one.html", context)


@login_required
def tickets_edit(request, pk):
    """ Edit a Single Ticket """
    ticket = get_object_or_404(Ticket, pk=pk)
    if request.method == "POST":
        ticket_form = TicketForm(request.POST, instance=ticket)
        if ticket_form.is_valid():
            ticket_form.instance.date_edited = timezone.now()
            ticket_form.save()
            messages.success(
                request, f"Ticket successfully updated!")
            return redirect(tickets_view_one, ticket.pk)
    else:
        ticket_form = TicketForm(instance=ticket)
    context = {
        "ticket": ticket,
        "ticket_form": ticket_form,
    }
    return render(request, "tickets_edit.html", context)


@login_required
def tickets_delete(request, pk):
    """ Delete a Ticket """
    ticket = get_object_or_404(Ticket, pk=pk)
    ticket.delete()
    messages.success(
        request, f"Your ticket has been deleted!")
    return redirect(tickets_view_all)


@login_required
def upvote_add(request, pk):
    """ Upvote a Ticket """
    ticket = get_object_or_404(Ticket, pk=pk)
    ticket.upvotes += 1
    # remove a ticket view to avoid duplicates
    ticket.views -= 1
    ticket.save()
    if request.method == "POST":
        donation_form = DonationForm(request.POST)
        if donation_form.is_valid():
            # amount to pay / donate
            donation_amount = 0
            donation_amount += int(request.POST.get("donation_amount"))
            try:
                # build Stripe payment
                token = request.POST["stripeToken"]
                customer = stripe.Charge.create(
                    amount=int(donation_amount * 100),
                    currency="EUR",
                    description=(
                        request.user.email +
                        " (" + request.user.get_full_name() + ")"),
                    source=token,
                )
            except stripe.error.CardError:
                # Stripe payment error
                messages.error(request, f"Your card was declined!")
            # authorization is valid - payment successful
            if customer.paid:
                Upvote.objects.create(
                    ticket_id=ticket.pk,
                    user_id=request.user.id)

project/tickets/templates/tickets_edit.html
{% extends "base.html" %}
{% load materializecss %}
{% load staticfiles %}
{% block title %} | Edit {{ ticket.ticket_type }} ({{ ticket.id }}){% endblock %}
{% block css %}
<style>
    body {
        background: url("{% static 'img/bg-unicorn-dark.png' %}") no-repeat center center fixed;
        background-size: cover;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col s12 center-align white-text">

            <form method="POST">
                {% csrf_token %}
                <div class="card form text-shadow-2">
                    <div class="card-content card-content-new-ticket">

                        <!-- top-right corner badge based on ticket status -->
                        {% include "partials/ticket_badge.html" %}

                        <!-- page title -->
                        <div class="row">
                            <div class="col s12">
                                <h1 class="bold">
                                    <span class="font-londrina {% include 'partials/ticket_type_color.html' %}-text">
                                        Edit {{ ticket.ticket_type }}
                                    </span>
                                </h1>
                            </div>
                        </div>

                        <!-- ticket title and description can be edited -->
                        <div class="row">
                            <div class="col s12 {% include 'partials/ticket_type_color.html' %}-text">
                                {{ ticket_form.title|materializecss:'icon=fas fa-file-alt' }}
                                {{ ticket_form.description|materializecss:'icon=fas fa-align-left' }}
                            </div>
                        </div>
                    </div>

                    <!-- submit and cancel buttons -->
                    <div class="card-action">
                        <div class="row">
                            <div class="col s12 m5 offset-m1">
                                <button type="submit" class="btn btn-large green bold text-shadow-2">Save
                                    <i class="fas fa-save material-icons right hide-on-small-and-down"
                                        aria-hidden="true"></i>
                                </button>
                            </div>
                            <div class="col s12 m5">
                                <button type="reset" class="btn btn-large red bold text-shadow-2" onclick="history.go(-1)">
                                    Cancel
                                    <i class="fas fa-times-circle material-icons right hide-on-small-and-down"
                                        aria-hidden="true"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock %}

project/tickets/templates/tickets_new_feature.html
{% extends "base.html" %}
{% load materializecss %}
{% load staticfiles %}
{% block title %} | New Ticket - Feature{% endblock %}
{% block css %}
<style>
    body {
        background: url("{% static 'img/bg-unicorn-dark.png' %}") no-repeat center center fixed;
        background-size: cover;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col s12 center-align white-text">

            <!-- form to add new Feature -->
            <form method="POST" action="{% url 'tickets_new_feature' %}" id="payment-form"
                data-token="{{ publishable }}" class="center-align">
                {% csrf_token %}
                <div class="card form text-shadow-2">
                    <div class="card-content card-content-new-ticket feature-text">

                        <!-- top-right corner 'badge' -->
                        <div class="card-badge-div">
                            <span class="card-badge card-badge-feature">
                                <i class="fas fa-magic fa-lg white-text" aria-hidden="true"></i>
                            </span>
                        </div>

                        <div class="row">
                            <div class="col s12">
                                <h1 class="bold upper font-londrina">
                                    New Feature
                                </h1>
                            </div>
                        </div>
                        <!-- ticket title and description fields -->
                        <div class="row">
                            <div class="col s12">
                                {{ ticket_form.title|materializecss:'icon=fas fa-file-alt' }}
                                {{ ticket_form.description|materializecss:'icon=fas fa-align-left' }}
                            </div>
                        </div>
                        <!-- slider to pick donation amount -->
                        <p class="range-field">
                            {{ donation_form.donation_amount }}
                        </p>
                        <small class="feature-text bold">SLIDE TO PICK DONATION AMOUNT</small>
                        <br><br>

                        <!-- Stripe Payment -->
                        <div class="row">
                            <div class="col s12">
                                <fieldset>
                                    <legend>
                                        <h1>
                                            <span class="white-text">Payment for</span>
                                            <span class="feature-text">
                                                &euro;<span id="total-cost"></span>
                                            </span>
                                        </h1>
                                    </legend>
                                    <label for="card-element">Credit or Debit card</label>
                                    <!-- Stripe widget inserted below -->
                                    <div id="card-element"></div>
                                    <div id="card-errors" class="white-text red" role="alert"></div>
                                </fieldset>
                            </div>
                        </div>
                    </div>

                    <div class="card-action">
                        <div class="row">
                            <div class="col s12 m5 offset-m1">
                                <!-- save / submit new feature + payment -->
                                <button type="submit" id="btn-pay" class="btn btn-large green bold text-shadow-2">
                                    Pay €<span id="btn-pay-span"></span>
                                    <i class="fas fa-hand-holding-usd right hide-on-small-and-down"
                                        aria-hidden="true"></i>
                                </button>
                            </div>
                            <div class="col s12 m5">
                                <!-- cancel payment / revert back to all tickets -->
                                <button type="reset" class="btn btn-large red bold text-shadow-2"
                                    onclick="history.go(-1)">
                                    Cancel
                                    <i class="fas fa-times-circle right hide-on-small-and-down" aria-hidden="true"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<!-- Stripe Payment API -->
<script src="https://js.stripe.com/v3/"></script>
<script>
    // Slider/Range Values
    defaultVal = $("#id_donation_amount").val();
    $("#btn-pay-span, #total-cost").text(defaultVal);
    $("input[type=range]").on("input", function () {
        $(".thumb .value").trigger("change");
        $("#btn-pay-span, #total-cost").text($(".thumb .value").text());
    });
</script>
<script src="{% static 'js/stripe.js' %}"></script>
{% endblock %}

project/tickets/templates/tickets_view_one.html
{% extends "base.html" %}
{% load humanize %}
{% load materializecss %}
{% load staticfiles %}
{% block title %} | Ticket ({{ ticket.ticket_type }}): {{ ticket.title }}{% endblock %}
{% block css %}
<style>
    body {
        background: url("{% static 'img/bg-unicorn-dark.png' %}") no-repeat center center fixed;
        background-size: cover;
    }
</style>
{% endblock %}

{% block content %}
<!-- set variable for 'today' -->
{% now "j F Y" as today %}

<div class="container">
    <div class="row">
        <div class="col s12">
            <div class="card form white-text text-shadow-2">

                <!-- top-right corner badge based on ticket status -->
                {% include "partials/ticket_badge.html" %}

                <div class="card-content white-text">
                    <div class="row">
                        <div class="col s12">
                            <!-- ticket type + ticket number -->
                            <h1 class="bold font-londrina center-align {% include 'partials/ticket_status_color.html' %}-text upper">
                                {{ ticket.ticket_type.ticket_type }} #{{ ticket.id }}
                            </h1>
                            <div class="divider"></div>
                            <div class="row">

                                <!-- TICKET DETAILS -->
                                <div class="col s12 m7">
                                    <br>
                                    <span class="{% include 'partials/ticket_status_color.html' %}-text bold upper">
                                        {{ ticket.ticket_type.ticket_type }} Title:
                                    </span>
                                    <h3 class="upper">
                                        {{ ticket.title }}
                                    </h3>
                                    <br>
                                    <span class="{% include 'partials/ticket_status_color.html' %}-text bold upper">
                                        {{ ticket.ticket_type.ticket_type }} Details:
                                    </span>
                                    <h4 class="justify tkt-description">
                                        {{ ticket.description|linebreaksbr }}
                                    </h4>
                                </div>

                                <!-- TICKET STATS -->
                                {% include "partials/ticket_stats.html" %}

                            </div>
                        </div>
                    </div>
                </div>

                <!-- UPVOTE PARTIAL -->
                {% include "partials/upvotes.html" %}
            </div>
            
            <div class="divider divider-rainbow"></div>

            <!-- COMMENTS PARTIAL -->
            {% include "partials/comments.html" %}
        </div>

        <div class="col s12 center-align">
            <div class="divider divider-rainbow"></div>
            <!-- back button to return to all tickets -->
            <span class="bold text-shadow-2">
                <a href="{% url 'tickets_view_all' %}"
                    class="btn btn-large {% include 'partials/ticket_status_color.html' %}">
                    Tickets
                    <i class="fas fa-chevron-circle-left left" aria-hidden="true"></i>
                </a>
            </span>
        </div>
    </div>


    <!-- MODAL - DELETE TICKET -->
    <div id="modal-tickets-delete" class="modal white-text">
        <div class="modal-content center-align bold">
            <h1 class="green-text">Confirm Deletion</h1>
            <h3>Are you sure you want to delete this {{ ticket.ticket_type }}?</h3>
            <p>This action cannot be undone.</p>
            <!-- delete ticket -->
            <a href="{% url 'tickets_delete' ticket.id %}" class="btn green text-shadow-2">
                <i class="far fa-trash-alt right" aria-hidden="true"></i>Yes
            </a>
            <!-- cancel - do not delete ticket -->
            <a class="btn modal-close red text-shadow-2">
                <i class="fas fa-reply right"></i>No
            </a>
        </div>
    </div>

</div>
{% endblock %}

{% block js %}
<!-- Stripe API and custom script -->
<script src="https://js.stripe.com/v3/"></script>
<script>
    // Slider/Range Values
    defaultVal = $("#id_donation_amount").val();
    $("#btn-pay-span, #total-cost").text(defaultVal);
    $("input[type=range]").on("input", function () {
        $(".thumb .value").trigger("change");
        $("#btn-pay-span, #total-cost").text($(".thumb .value").text());
    });
</script>
<script src="{% static 'js/stripe.js' %}"></script>
{% endblock %}